FROM slacgismo/circleci_python37_base
ENV container docker

RUN sudo apt-get update
RUN sudo apt-get install autoconf
RUN sudo apt-get install automake
RUN sudo apt-get install libtool
RUN sudo apt-get install libxerces-c-dev
RUN sudo apt-get install libmysqlcppconn-dev
RUN sudo apt-get install libarmadillo-dev
RUN sudo apt-get install ncurses-dev
RUN sudo apt-get install doxygen
